-- AlterTable
ALTER TABLE "rfq_quotes" ADD COLUMN     "make" TEXT NOT NULL DEFAULT 'Unbranded',
ADD COLUMN     "model" TEXT NOT NULL DEFAULT 'Generic',
ADD COLUMN     "quotedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "regretted" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "rate" DROP NOT NULL;
